### ISSUE TITLE
Detalhes de seminário sem filho dá erro interno

### ISSUE THREAD

**Issue by renevs** [aderleifilho/SeminarioIME#3]
Detalhes do seminário sem filhos dá erro interno. (Quando testei, o id 11)
Abaixo a correção que eu cheguei a testar, que é na chamada JSON.

    public static ArrayList<JSONObject> getAttendanceList(String pSeminarId) {
        JSONObject responseFromAsyncTask;
        URL url;
        Seminar seminar = new Seminar();
        seminar.setSeminarId(pSeminarId);
        ArrayList<JSONObject> studentList = new ArrayList<>();

        try {
            url = new URL(RestRoutes.GET_ATTENDANCE_LIST);
            responseFromAsyncTask = getInstance().execute(url, POST, seminar).get();
            Log.e(CLASS_NAME, responseFromAsyncTask.toString());
            if (responseFromAsyncTask != null && responseFromAsyncTask.getBoolean("success")) {
                if ( responseFromAsyncTask.has( "data" ) ) {
                    JSONArray ja = responseFromAsyncTask.getJSONArray("data");
                    if (ja != null) {
                        for (int i = 0; i < ja.length(); i++) {
                            studentList.add(ja.getJSONObject(i));
                        }
                    }
                }
            }
            return studentList;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

**Comment by acorsza** [comment]
Fixed.
